### ISSUE TITLE
Rules Error: Invalid request while validating conditions

### ISSUE THREAD

**Issue by riusi88** [barrelstrength/sprout-forms#590]
### Description
After updating to the most recent version of the plugin and Craft CMS, and creating a Form with some rules, I receive this JS error: "Invalid request while validating conditions".

### Steps to reproduce

1. Create Form, and add a multiple choice field (3 options) and 3 dropdown fields. 
2. Create 3 rules based on the multiple choice field options. The rule should unhide one of the 3 dropdowns
3. Load form into template
4. The dropdown fields are hidden on page load (as expected), but selecting any of the multiple choice options does not unhide any of the hidden fields. 
4.  Open browser console, and see JS error "JSON.parse: unexpected character at line 2 column 1 of the JSON data" or "Invalid request while validating conditions"

### Additional info
I uniminified the JS file, and the error is logged on line 1076 and 1084 of the rules.js file. This issue is occuring on the production environment, but I also made sure to load the form into a basic HTML page to avoid any markup issues and JS conflicts. 

- Craft version: 3.7.13
- PHP version: 7.3.29
- Database driver & version:  MySQL 5.5.5
- Sprout Forms: 3.13.7

**Comment by BenParizek** [comment]
@riusi88 If this remains an issue, I may need more info to help troubleshoot. In a simple test, I'm seeing the expected behavior and no console errors. https://cln.sh/EiH0qg

If you haven't already, as a starting point to troubleshoot further I'd try to create a copy of your db, delete all other fields except the ones in question, and try to output the form on a simple page to confirm that is working, and then start adding back complexity. I'll need more info on your full form setup (fields, rules, and templates) to help troubleshoot further.
